server:
  port: 8080
  shutdown: graceful


spring:
  main:
    banner-mode: off
    web-application-type: servlet
  application:
    name: mobile-server
  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/client?currentSchema=mobile_server"
    password: "P@55w0rd"
    username: "client"
    hikari:
      minimumIdle: 1
      maximumPoolSize: 3
      autoCommit: false
      connectionTestQuery: SELECT 1
  flyway:
    enabled: true
    locations: "classpath:db/migration"
    url: "jdbc:postgresql://localhost:5432/client"
    password: "P@55w0rd"
    username: "client"
    schemas: "mobile_server"